handle errors, new data parse, still support old

diff --git a/tureng b/tureng
--- a/tureng
+++ b/tureng
@@ -9,15 +9,21 @@
 
 mkdir -p ${HOME}/.cache/tureng/
 
-#### TODO vim stucks with this. (for vim-tureng) ############
-#                                                           #
-# pgrep tureng-api &>/dev/null || tureng-api &! &>/dev/null #
-#                                                           #
-#############################################################
-
 ( [ $# -gt 0 ] && echo $@ || cat /dev/stdin ) | while read args; do
 	phrase=$(echo $args | sed 's/ /+/g' | tr '[:upper:]' '[:lower:]');
 	file=${HOME}/.cache/tureng/$phrase.json;
-	curl -so $file "localhost:8080/translate/$phrase" &&
-	cat $file | jq -r '.response|.[]|.target' | uniq;
+	if ! [ -s $file ]; then
+		pgrep tureng-api &>/dev/null || { echo tureng-api is not up.; exit 1; }
+		curl -so $file "localhost:8080/translate/$phrase" ||
+			{ >&2 echo "`basename $0`: connection error"; exit 2; }
+	fi
+	if [[ $(cat $file | jq -r '.response|.[]|.target' | uniq) == "null" ]]; then
+		if ! [[ $(cat $file | jq -r '.response|.[]|.tr' | uniq) ]]; then
+			>&2 echo "`basename $0`: $phrase: no such phrase"; exit 2;
+		else
+			cat $file | jq -r '.response|.[]|.tr' | uniq
+		fi
+	else
+		cat $file | jq -r '.response|.[]|.target' | uniq
+	fi
 done
